name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: RyanDsilva
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, repositories
          template: classic

          config_timezone: Asia/Calcutta
          config_padding: 0, -50%

          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

          plugin_introduction: yes

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_languages: yes
          plugin_languages_analysis_timeout: 30
          plugin_languages_categories: programming
          plugin_languages_colors: github
          plugin_languages_limit: 6
          plugin_languages_recent_categories: programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 5%

          plugin_repositories: yes
          plugin_repositories_featured: RyanDsilva/feature_folder_cli

          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes



          output_action: commit
          committer_branch: master
          committer_message: "chore: update metrics"
          filename: my-metrics.svg
