name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: RyanDsilva
          template: classic
          base: header, activity, community, repositories, metadata
          base_hireable: yes
          config_display: columns
          config_octicon: yes
          config_padding: 0, 5%
          config_timezone: America/Indianapolis
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B
          plugin_calendar: yes
          plugin_calendar_limit: 1
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_ignored: html, css, markdown
          plugin_languages_limit: 8
          plugin_languages_other: yes
          plugin_languages_recent_categories: programming
          plugin_languages_recent_days: 30
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_pagespeed: yes
          plugin_pagespeed_url: https://ryandsilva.dev
          plugin_repositories: yes
          plugin_repositories_featured: RyanDsilva/feature_folder_cli
          plugin_repositories_order: featured, pinned, starred, random
          plugin_repositories_pinned: 2
          plugin_repositories_starred: 2
          repositories_affiliations: owner, contributor
          optimize: svg
          experimental_features: --optimize-svg
          filename: 'my-metrics.svg'
          output_action: none

      - name: Push Metrics
        run: |
          set +e
          git checkout metrics-renders
          git config user.name ryan-dsilva[bot]
          git config user.email bot@ryandsilva.dev
          sudo mv /metrics_renders/* ./
          git add --all
          git commit -m "chore: push metrics"
          git push

